name: CI

on: [pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build

      - name: Run unit test suites
        env:
          CI: true
        run: yarn test

      - name: Run linter
        run: yarn lint
